### ISSUE TITLE
Installation Windows

### ISSUE THREAD

**Issue by rudi59** [gammu/python-gammu#15]
Is it possible to install/compile python-gammu in windows? i have some errors with install in windows.

**Comment by nijel** [comment]
Yes it's possible, but there is slight problem in getting Gammu built by same MSVC version as Python. So you most likely will have to build Gammu as well.

**Comment by ktngoykalolo** [comment]
hello struggling as well to install the Python-gammu package on Visual Studio. trying out the VS tools for Python. when importing the package it fails. any help ?

**Comment by nijel** [comment]
What error do you get? Maybe you just need to copy Gammu.dll somewhere it can find it?

**Comment by ktngoykalolo** [comment]
I have PTVS on VS 2015. (community edition) . I have installed Python via the Anaconda tooling. 
I have tried adding it via pip, easy_install or conda, only pip says that it doesn't find the gammu files. 
it fails to install.

**Comment by rudi59** [comment]
At the Moment i can only compile Gammu self with VS 2015. python-gammu has Errors in smsd.c - if i compile without gammu-smsd VS can not Link the Build correctly. Maybe there are some dependencies not corretly installed on my System, i dont know it exactly at the Moment. I also modified my gammu.pc (pkgconfig) VS don´t need a libm

**Comment by ktngoykalolo** [comment]
@rudi59 could you give me more details on how you compile Gammu on VS 2015 ? 
I am considering porting this project on .NET via native bindings.

**Comment by nijel** [comment]
rudi59 píše v Po 20. 02. 2017 v 11:10 -0800:
> At the Moment i can only compile Gammu self with VS 2015. python-
> gammu has Errors in smsd.c - if i compile without gammu-smsd VS can
> not Link the Build correctly. Maybe there are some dependencies not
> corretly installed on my System, i dont know it exactly at the
> Moment. I also modified my gammu.pc (pkgconfig) VS don´t need a libm

Can you share these changes, so that they can be integrated upstream?

**Comment by rudi59** [comment]
@ktngoykalolo For Gammu you need minimum cmake and doxygen installed. with cmake -G  "Visual Studio 14 2015" you can create a Visual Studio 2015 Gammu.sln. All other dependencies are listed her https://wammu.eu/docs/manual/project/install.html#compiling-on-microsoft-windows To compile you need Windows SDK and C++ Headers in Community Edtion. 

@nijel Yes i would share any changes, at the Moment i don´t have any solution for the Errors in smsd.c and the Linker Problem. 
In gammu.pc (and gammu-smsd.pc) for Windows 

gammu-smsd.pc: 
"Libs: -L${libdir} -lgsmsd -lm"  changed to 
"Libs: -L${libdir} -lgsmsd"   

gammu.pc: 
"Libs: -L${libdir} -lgsmsd -lm"  changed to 
"Libs: -L${libdir} -lgsmsd"

If you Need, i can provide a diff file.

**Comment by ktngoykalolo** [comment]
@nijel here are the results I get when trying to add python-gammu on the project : 

Collecting python-gammu
  Using cached python-gammu-2.7.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 69, in _spawn_nt
        rc = os.spawnv(os.P_WAIT, executable, cmd)
    FileNotFoundError: [Errno 2] No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Kevin\AppData\Local\Temp\pip-build-751bgc3t\python-gammu\setup.py", line 110, in <module>
        check_minimum_gammu_version()
      File "C:\Users\Kevin\AppData\Local\Temp\pip-build-751bgc3t\python-gammu\setup.py", line 45, in check_minimum_gammu_version
        "gammu"
      File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 75, in _spawn_nt
        "command %r failed: %s" % (cmd, exc.args[-1]))
    distutils.errors.DistutilsExecError: command 'pkg-config' failed: No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Kevin\AppData\Local\Temp\pip-build-751bgc3t\python-gammu\
'python-gammu' failed to install. Exit code: 1

**Comment by ktngoykalolo** [comment]
here is the result with easy_install : 
`Installing 'python-gammu'
Searching for python-gammu
Reading https://pypi.python.org/simple/python-gammu/
Downloading https://pypi.python.org/packages/ee/ec/1ed4c72ae1399edcf7f450798d52dd6b2d54bd85056a8b9fd698fabdfbac/python-gammu-2.7.tar.gz#md5=16c668d9a2334f5301182f0a7e8feb59
Best match: python-gammu 2.7
Processing python-gammu-2.7.tar.gz
Writing C:\Users\Kevin\AppData\Local\Temp\easy_install-1u6skrx8\python-gammu-2.7\setup.cfg
Running python-gammu-2.7\setup.py -q bdist_egg --dist-dir C:\Users\Kevin\AppData\Local\Temp\easy_install-1u6skrx8\python-gammu-2.7\egg-dist-tmp-56hgz2yz
error: command 'pkg-config' failed: No such file or directory
'python-gammu' failed to install. Exit code: 1
`

**Comment by nijel** [comment]
@rudi59 Feel free to report errors in building. The `-lm` issue should be fixed as of gammu/gammu@c845917fd

**Comment by nijel** [comment]
@ktngoykalolo Install pkg-config.

**Comment by nijel** [comment]
Looking at https://wiki.python.org/moin/WindowsCompilers, the official binaries should be compatible with Python 3.5 and 3.6. In that case you don't need to build it, just install (and ensure pkg-config finds it).

**Comment by rudi59** [comment]
There are several issue on Windows. I attached some patch files for misc.c, smsd.c and convertors\base.c
[patch.zip](https://github.com/gammu/python-gammu/files/796044/patch.zip)
please review this changes.

i can minimsize the errors, but some of them are still existing on linking. i work on it.

`base.obj : error LNK2019: unresolved external symbol _strcasecmp referenced in f
unction _BoolFromPython
diverts.obj : error LNK2001: unresolved external symbol _strcasecmp
gammu.obj : error LNK2001: unresolved external symbol _strcasecmp
gsmsd.lib(core.obj) : error LNK2019: unresolved external symbol _GSM_StringArray
_New referenced in function _SMSD_NewConfig
gsmsd.lib(core.obj) : error LNK2019: unresolved external symbol _GSM_StringArray
_Free referenced in function _SMSD_FreeConfig
gsmsd.lib(core.obj) : error LNK2019: unresolved external symbol _GSM_StringArray
_Add referenced in function _SMSD_LoadIniNumbersList
gsmsd.lib(core.obj) : error LNK2019: unresolved external symbol _GSM_StringArray
_Find referenced in function _SMSD_CheckRemoteNumber
gsmsd.lib(core.obj) : error LNK2019: unresolved external symbol _round reference
d in function _SMSD_MainLoop
gsmsd.lib(sql.obj) : error LNK2019: unresolved external symbol _strptime referen
ced in function _SMSDSQL_ParseDate
Gammu.lib(s60phone.obj) : error LNK2001: unresolved external symbol _strcasestr
Gammu.lib(gsmlogo.obj) : error LNK2019: unresolved external symbol _strcasestr r
eferenced in function _GSM_SaveBitmapFile
Gammu.lib(gsmback.obj) : error LNK2001: unresolved external symbol _strcasestr
Gammu.lib(gsmstate.obj) : error LNK2001: unresolved external symbol _strcasestr
Gammu.lib(atgen.obj) : error LNK2001: unresolved external symbol _strcasestr
Gammu.lib(gsmstate.obj) : error LNK2019: unresolved external symbol __imp__SHGet
FolderPathA@20 referenced in function _GSM_FindGammuRC
Gammu.lib(dummy.obj) : error LNK2019: unresolved external symbol _closedir refer
enced in function _DUMMY_Terminate
Gammu.lib(dummy.obj) : error LNK2019: unresolved external symbol _readdir refere
nced in function _DUMMY_GetFolderListing
Gammu.lib(dummy.obj) : error LNK2019: unresolved external symbol _opendir refere
nced in function _DUMMY_GetFolderListing
Gammu.lib(at-sms.obj) : error LNK2019: unresolved external symbol _strchrnul ref
erenced in function _ATGEN_ReplyGetSMSMemories`

**Comment by nijel** [comment]
Thanks, I've merged these changes.

**Comment by nijel** [comment]
I've managed to fix compilation and automate it on AppVeoyr, so the binaries are now produced for every commit and will be included in upcoming releases.

* Python 3.6: https://ci.appveyor.com/project/nijel/python-gammu/build/22/job/ivfwk7867ovt677j/artifacts
* Python 3.5: https://ci.appveyor.com/project/nijel/python-gammu/build/22/job/28f300881whsasyu/artifacts
