### ISSUE TITLE
service-numbers.py seems not to work

### ISSUE THREAD

**Issue by oprema** [gammu/python-gammu#3]
Hi,
I wanted to use the python example service-numbers.py but as far as I can say it seems to have a bug.
If I use gammu (gammu getussd *100#) I get the left credits (in €) of my Prepaid Card just like I want to.
However if I use service-numbers.py, which should accomplish the same, I always get status: Terminated and no further info. I am using a Huawei E!60 USB-Device with a Raspberrypi 2 OS: Jessie

Below you find the logfiles:
- for gammu getussd *100#

```
[Gammu            - 1.33.0 built 08:46:05 Aug 14 2013 using GCC 4.6]
[Connection       - "at19200"]
[Connection index - 0]
[Model type       - ""]
[Device           - "/dev/ttyUSB1"]
[Running on       - Linux, kernel 4.1.7-v7+ (#817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015)]
Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Setting speed to 19200
[Module           - "auto"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Getting model
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
1 "AT+CGMM"
2 "E160"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x16/22
41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|311|366|300|0D |0A  AT+CGMM...E160..
0D |0A |4FO|4BK|0D |0A                                          ..OK..          
[Model name: `E160']
[Model data: `E160']
[Model data: `E160']
1 "^BOOT:30275962,0,0,0,75"
Checking line: ^BOOT:30275962,0,0,0,75
AT reply state: 4
RECEIVED frametype 0x00/length 0x19/25
5E^|42B|4FO|4FO|54T|3A:|333|300|322|377|355|399|366|322|2C,|300 ^BOOT:30275962,0
2C,|300|2C,|300|2C,|377|355|0D |0A                              ,0,0,75..       
[Connected model  - "E160"]
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
[Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
Setting date & time
SENDING frametype 0x00/length 0x21/33
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|322|3A:|355|311|3A:|355|399|2B+|300|300|22" /01,12:51:59+00"
0D                                                              .               
1 "AT+CCLK="2015/10/01,12:51:59+00""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x27/39
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|322|3A:|355|311|3A:|355|399|2B+|300|300|22" /01,12:51:59+00"
0D |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Getting firmware versions
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
1 "AT+CGMR"
2 "11.604.18.01.00"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|366|300|344 AT+CGMR...11.604
2E.|311|388|2E.|300|311|2E.|300|300|0D |0A |0D |0A |4FO|4BK|0D  .18.01.00....OK.
0A                                                              .               
Received firmware version: "11.604.18.01.00"
Number version is "11.604180"
[Firmware version - "11.604.18.01.00"]
[Connected]
Entering GSM_SetIncomingUSSD
Enabling incoming USSD
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.      
1 "AT+CUSD=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Leaving GSM_SetIncomingUSSD
Entering GSM_DialService
SENDING frametype 0x00/length 0x1A/26
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D                          C3602",15.      
1 "AT+CUSD=1,"AA180C3602",15"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x20/32
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D |0D |0A |4FO|4BK|0D |0A  C3602",15...OK..
Incoming USSD received
Leaving GSM_DialService
1 "+CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15"
Checking line: +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
AT reply state: 4
RECEIVED frametype 0x00/length 0x46/70
2B+|43C|55U|53S|44D|3A:|20 |300|2C,|22"|41A|300|45E|300|399|41A +CUSD: 0,"A0E09A
355|45E|322|46F|42B|333|44D|399|45E|355|333|399|45E|388|355|388 5E2FB3D9E539E858
41A|377|41A|333|43C|333|45E|322|42B|322|355|42B|300|377|43C|41A A7A3C3E2B25B07CA
42B|399|377|322|333|311|355|300|42B|311|322|41A|377|355|300|311 B9723150B12A7501
22"|2C,|311|355|0D |0A                                          ",15..          
Incoming USSD received
Parsing +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
 with +CUSD: @i @0
Parsed int 0
Status: 0
Parsing +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
 with +CUSD: @i, @r, @i @0
Parsed int 0
Grabbed string from reply: "A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501" (parsed 56 bytes)
Parsed raw string "A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501"
Parsed int 15
1 "^RSSI:22"
Checking line: ^RSSI:22
AT reply state: 4
RECEIVED frametype 0x00/length 0x0A/10
5E^|52R|53S|53S|49I|3A:|322|322|0D |0A                          ^RSSI:22..      
1 "^RSSI:22"
Checking line: ^RSSI:22
AT reply state: 4
RECEIVED frametype 0x00/length 0x0A/10
5E^|52R|53S|53S|49I|3A:|322|322|0D |0A                          ^RSSI:22..      
```
- for service-numbers.py

```
[Gammu            - 1.33.0 built 08:46:05 Aug 14 2013 using GCC 4.6]
[Connection       - "at19200"]
[Connection index - 0]
[Model type       - ""]
[Device           - "/dev/ttyUSB1"]
[Running on       - Linux, kernel 4.1.7-v7+ (#817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015)]
Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Setting speed to 19200
[Module           - "auto"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Getting model
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
1 "AT+CGMM"
2 "E160"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x16/22
41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|311|366|300|0D |0A  AT+CGMM...E160..
0D |0A |4FO|4BK|0D |0A                                          ..OK..          
[Model name: `E160']
[Model data: `E160']
[Model data: `E160']
[Connected model  - "E160"]
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
[Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
Setting date & time
SENDING frametype 0x00/length 0x21/33
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|322|3A:|355|311|3A:|344|311|2B+|300|300|22" /01,12:51:41+00"
0D                                                              .               
1 "AT+CCLK="2015/10/01,12:51:41+00""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x27/39
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|322|3A:|355|311|3A:|344|311|2B+|300|300|22" /01,12:51:41+00"
0D |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Getting firmware versions
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
1 "AT+CGMR"
2 "11.604.18.01.00"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|366|300|344 AT+CGMR...11.604
2E.|311|388|2E.|300|311|2E.|300|300|0D |0A |0D |0A |4FO|4BK|0D  .18.01.00....OK.
0A                                                              .               
Received firmware version: "11.604.18.01.00"
Number version is "11.604180"
[Firmware version - "11.604.18.01.00"]
[Connected]
Entering GSM_SetIncomingUSSD
Enabling incoming USSD
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.      
1 "AT+CUSD=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Leaving GSM_SetIncomingUSSD
Entering GSM_DialService
SENDING frametype 0x00/length 0x1A/26
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D                          C3602",15.      
1 "AT+CUSD=1,"AA180C3602",15"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x20/32
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D |0D |0A |4FO|4BK|0D |0A  C3602",15...OK..
Incoming USSD received
Leaving GSM_DialService
Entering GSM_SetIncomingSMS
Getting available SMS memories
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|50P|4DM|53S|3D=|3F?|0D                          AT+CPMS=?.      
1 "AT+CPMS=?"
2 "+CPMS: ("ME","MT","SM","SR"),("ME","MT","SM","SR"),("ME","MT","SM","SR")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x5C/92
41A|54T|2B+|43C|50P|4DM|53S|3D=|3F?|0D |0D |0A |2B+|43C|50P|4DM AT+CPMS=?...+CPM
53S|3A:|20 |28(|22"|4DM|45E|22"|2C,|22"|4DM|54T|22"|2C,|22"|53S S: ("ME","MT","S
4DM|22"|2C,|22"|53S|52R|22"|29)|2C,|28(|22"|4DM|45E|22"|2C,|22" M","SR"),("ME","
4DM|54T|22"|2C,|22"|53S|4DM|22"|2C,|22"|53S|52R|22"|29)|2C,|28( MT","SM","SR"),(
22"|4DM|45E|22"|2C,|22"|4DM|54T|22"|2C,|22"|53S|4DM|22"|2C,|22" "ME","MT","SM","
53S|52R|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A                  SR")....OK..    
Available SMS memories received: read: ME : ok, SM : ok, save: ME : ok, SM = ok, Motorola = no
Setting SMS memory type to ME
SENDING frametype 0x00/length 0x0D/13
41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|0D              AT+CPMS="ME".   
1 "AT+CPMS="ME""
2 "+CPMS: 0,23,0,20,0,20"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2C/44
41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|0D |0D |0A |2B+ AT+CPMS="ME"...+
43C|50P|4DM|53S|3A:|20 |300|2C,|322|333|2C,|300|2C,|322|300|2C, CPMS: 0,23,0,20,
300|2C,|322|300|0D |0A |0D |0A |4FO|4BK|0D |0A                  0,20....OK..    
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4EN|4DM|49I|3D=|3F?|0D                          AT+CNMI=?.      
1 "AT+CNMI=?"
2 "+CNMI: (0,1,2),(0,1,2,3),(0,2),(0,1,2),(0,1)"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x40/64
41A|54T|2B+|43C|4EN|4DM|49I|3D=|3F?|0D |0D |0A |2B+|43C|4EN|4DM AT+CNMI=?...+CNM
49I|3A:|20 |28(|300|2C,|311|2C,|322|29)|2C,|28(|300|2C,|311|2C, I: (0,1,2),(0,1,
322|2C,|333|29)|2C,|28(|300|2C,|322|29)|2C,|28(|300|2C,|311|2C, 2,3),(0,2),(0,1,
322|29)|2C,|28(|300|2C,|311|29)|0D |0A |0D |0A |4FO|4BK|0D |0A  2),(0,1)....OK..
Parsing range: (0,1,2),(0,1,2,3),(0,2),(0,1,2),(0,1)
Returning range: 0, 1, 2, -1
Parsing range: (0,1,2,3),(0,2),(0,1,2),(0,1)
Returning range: 0, 1, 2, 3, -1
Parsing range: (0,2),(0,1,2),(0,1)
Returning range: 0, 2, -1
Parsing range: (0,1,2),(0,1)
Returning range: 0, 1, 2, -1
Leaving GSM_SetIncomingSMS
Entering GSM_SetIncomingCall
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|43C|57W|41A|3D=|300|0D                          AT+CCWA=0.      
1 "AT+CCWA=0"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|43C|57W|41A|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CCWA=0...OK..
Disabling incoming call notification
Leaving GSM_SetIncomingCall
Entering GSM_SetIncomingCB
Leaving GSM_SetIncomingCB
Entering GSM_SetIncomingUSSD
Terminating possible incoming USSD
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D                          AT+CUSD=2.      
1 "AT+CUSD=2"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=2...OK..
Disabling incoming USSD
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D                          AT+CUSD=0.      
1 "+CUSD: 2"
Checking line: +CUSD: 2
AT reply state: 4
RECEIVED frametype 0x00/length 0x0A/10
2B+|43C|55U|53S|44D|3A:|20 |322|0D |0A                          +CUSD: 2..      
Incoming USSD received
Parsing +CUSD: 2
 with +CUSD: @i @0
Parsed int 2
Status: 2
Parsing +CUSD: 2
 with +CUSD: @i, @r, @i @0
Parsed int 2
Parsing +CUSD: 2
 with +CUSD: @i, @r @0
Parsed int 2
1 "AT+CUSD=0"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=0...OK..
Leaving GSM_SetIncomingUSSD
[Terminating]
[Closing]
```

**Comment by nijel** [comment]
Is it consistently broken like this? The logs do not show any difference which could cause it...

Anyway just to be safe, can you try with latest python-gammu and gammu? There have been quite a lot of fixes meanwhile....

**Comment by oprema** [comment]
I tried it with wheezy and it didn't work there either, but wheezy is even older. I'll try to compile the newest version and let you know how it went.

**Comment by oprema** [comment]
Ok, grabbed the latest versions of gammu and python-gammu. Removed the installed versions on my Raspi and compiled and installed the new ones.
Here are some outputs:

which gammu
/usr/local/bin/gammu

gammu version
[Gammu version 1.36.6]

gammu getussd *100#
Press Ctrl+C to break...
USSD received
Status               : No action needed
Service reply        : " Aktuelles Guthaben: 9.91 EUR."

./service_numbers.py ~/.gammurc *100#
This example shows interaction with network using service codes
Talking to network...
Network reply:
Status: Terminated

As you can see the error persists. Bug? Or anything I do wrong?
Thanks ... great program!

**Comment by nijel** [comment]
I've fixed one bug I found in the script, hopefully it really fixes your issue...

**Comment by oprema** [comment]
Hmmm your change made service_numbers.py hang badly. I tried several times.

./service_numbers.py ~/.gammurc *100#
This example shows interaction with network using service codes
Talking to network...

Killing the process left gammu not working either.

**Comment by nijel** [comment]
Indeed the waiting delay is too long, I've shortened it.

Anyway this just makes the problem of not receiving any reply more visible. Can you please post log from the latest version as well?

**Comment by oprema** [comment]
Hi,

ok, I pulled the latest changes and compiled and installed python-gammu again. Executing ./service_numbers.py ~/.gammurc *100# still hangs the program. Below is the log.


[Gammu            - 1.36.6]
[Connection       - "at19200"]
[Connection index - 0]
[Model type       - ""]
[Device           - "/dev/ttyUSB1"]
[Running on       - Linux, kernel 4.1.7-v7+ (#817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015)]
Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Setting speed to 19200
[Module           - "auto"]
Escaping SMS mode
SENDING frame type 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frame type 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frame type 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "^BOOT:30275962,0,0,0,75"
2 "AT+MODE=2"
3 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x2C/44
5E^|42B|4FO|4FO|54T|3A:|333|300|322|377|355|399|366|322|2C,|300 ^BOOT:30275962,0
2C,|300|2C,|300|2C,|377|355|0D |0A |41A|54T|2B+|4DM|4FO|44D|45E ,0,0,75..AT+MODE
3D=|322|0D |0D |0A |45E|52R|52R|4FO|52R|0D |0A                  =2...ERROR..    
Seems not to be supported
Enabling CME errors
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "IRA""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|49I|52R|41A|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "IRA"....OK.. 
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
SENDING frame type 0x00/length 0x0E/14
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D          AT+CSCS="GSM".  
1 "AT+CSCS="GSM""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D |0D |0A  AT+CSCS="GSM"...
4FO|4BK|0D |0A                                                  OK..            
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
Getting model
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
1 "AT+CGMM"
2 "E160"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x16/22
41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|311|366|300|0D |0A  AT+CGMM...E160..
0D |0A |4FO|4BK|0D |0A                                          ..OK..          
[Model name: `E160']
[Model data: `E160']
[Model data: `E160']
[Connected model  - "E160"]
Checking for OBEX support
SENDING frame type 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frame type 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
SENDING frame type 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
[Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Escaping SMS mode
SENDING frame type 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frame type 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frame type 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "huawei"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x18/24
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Manufacturer info received
[Manufacturer: Huawei]
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Checking for OBEX support
SENDING frame type 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frame type 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
SENDING frame type 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
Setting date & time
SENDING frame type 0x00/length 0x21/33
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|355|3A:|344|399|3A:|311|355|2B+|300|300|22" /01,15:49:15+00"
0D                                                              .               
1 "AT+CCLK="2015/10/01,15:49:15+00""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x27/39
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|311|300 AT+CCLK="2015/10
2F/|300|311|2C,|311|355|3A:|344|399|3A:|311|355|2B+|300|300|22" /01,15:49:15+00"
0D |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Getting firmware versions
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
1 "AT+CGMR"
2 "11.604.18.01.00"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|366|300|344 AT+CGMR...11.604
2E.|311|388|2E.|300|311|2E.|300|300|0D |0A |0D |0A |4FO|4BK|0D  .18.01.00....OK.
0A                                                              .               
Received firmware version: "11.604.18.01.00"
Number version is "11.604180"
[Firmware version - "11.604.18.01.00"]
[Connected]
Entering GSM_SetIncomingUSSD
Enabling incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.      
1 "AT+CUSD=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Leaving GSM_SetIncomingUSSD
Entering GSM_DialService
SENDING frame type 0x00/length 0x1A/26
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D                          C3602",15.      
1 "AT+CUSD=1,"AA180C3602",15"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x20/32
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|41A|41A|311|388|300 AT+CUSD=1,"AA180
43C|333|366|300|322|22"|2C,|311|355|0D |0D |0A |4FO|4BK|0D |0A  C3602",15...OK..
Incoming USSD received
Leaving GSM_DialService
Entering GSM_SetIncomingSMS
Getting available SMS memories
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|50P|4DM|53S|3D=|3F?|0D                          AT+CPMS=?.      
1 "^RSSI:21"
2 "AT+CPMS=?"
3 "+CPMS: ("ME","MT","SM","SR"),("ME","MT","SM","SR"),("ME","MT","SM","SR")"
4 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x66/102
5E^|52R|53S|53S|49I|3A:|322|311|0D |0A |41A|54T|2B+|43C|50P|4DM ^RSSI:21..AT+CPM
53S|3D=|3F?|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |28(|22"|4DM S=?...+CPMS: ("M
45E|22"|2C,|22"|4DM|54T|22"|2C,|22"|53S|4DM|22"|2C,|22"|53S|52R E","MT","SM","SR
22"|29)|2C,|28(|22"|4DM|45E|22"|2C,|22"|4DM|54T|22"|2C,|22"|53S "),("ME","MT","S
4DM|22"|2C,|22"|53S|52R|22"|29)|2C,|28(|22"|4DM|45E|22"|2C,|22" M","SR"),("ME","
4DM|54T|22"|2C,|22"|53S|4DM|22"|2C,|22"|53S|52R|22"|29)|0D |0A  MT","SM","SR")..
0D |0A |4FO|4BK|0D |0A                                          ..OK..          
1 "+CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15"
Checking line: +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
AT reply state: 4
RECEIVED frame type 0x00/length 0x46/70
2B+|43C|55U|53S|44D|3A:|20 |300|2C,|22"|41A|300|45E|300|399|41A +CUSD: 0,"A0E09A
355|45E|322|46F|42B|333|44D|399|45E|355|333|399|45E|388|355|388 5E2FB3D9E539E858
41A|377|41A|333|43C|333|45E|322|42B|322|355|42B|300|377|43C|41A A7A3C3E2B25B07CA
42B|399|377|322|333|311|355|300|42B|311|322|41A|377|355|300|311 B9723150B12A7501
22"|2C,|311|355|0D |0A                                          ",15..          
Incoming USSD received
Parsing +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
 with +CUSD: @i @0
Parsed int 0
Status: 0
Parsing +CUSD: 0,"A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501",15
 with +CUSD: @i, @r, @i @0
Parsed int 0
Grabbed string from reply: "A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501" (parsed 56 bytes)
Parsed raw string "A0E09A5E2FB3D9E539E858A7A3C3E2B25B07CAB9723150B12A7501"
Parsed int 15
1 "^RSSI:21"
Checking line: ^RSSI:21
AT reply state: 4
RECEIVED frame type 0x00/length 0x0A/10
5E^|52R|53S|53S|49I|3A:|322|311|0D |0A                          ^RSSI:21..      
1 "^BOOT:30275962,0,0,0,75"
Checking line: ^BOOT:30275962,0,0,0,75
AT reply state: 4
RECEIVED frame type 0x00/length 0x19/25
5E^|42B|4FO|4FO|54T|3A:|333|300|322|377|355|399|366|322|2C,|300 ^BOOT:30275962,0
2C,|300|2C,|300|2C,|377|355|0D |0A                              ,0,0,75..       
1 "^BOOT:30275962,0,0,0,75"
Checking line: ^BOOT:30275962,0,0,0,75
AT reply state: 4
RECEIVED frame type 0x00/length 0x19/25
5E^|42B|4FO|4FO|54T|3A:|333|300|322|377|355|399|366|322|2C,|300 ^BOOT:30275962,0
2C,|300|2C,|300|2C,|377|355|0D |0A                              ,0,0,75..

**Comment by nijel** [comment]
Okay, so it does receive it now, but doesn't seem to appear in the python side. I've added some debugging code to help us indentify what went wrong. Can you please update python-gammu?

**Comment by oprema** [comment]
Hi Michal,

I've pulled your changes and compiled them. The output looks like that now:
./service_numbers.py ~/.gammurc *100#
This example shows interaction with network using service codes
Talking to network...
python-gammu: WARNING: Adding USSD to queue, position 0
Network reply:
Status: Terminated

Thanks for all your efforts.

**Comment by nijel** [comment]
Most likely this is bug in Gammu library, which has been fixed for latest release (see https://github.com/gammu/gammu/issues/239). Can you please test that?

**Comment by nijel** [comment]
Closing as this presumably has been fixed in Gammu.
