### ISSUE TITLE
SMSD test does not pass

### ISSUE THREAD

**Issue by awilfox** [gammu/python-gammu#6]
When running the test suite for python-gammu 2.5 under any of Python 2.7.11, 3.4.3, 3.5.1 on x86_64 Linux, I receive the following error:

```
test_smsd (test.test_smsd.SMSDDummyTest) ... Log filename is "stderr"
Fri 2016/01/22 01:14:31 python-gammu[541]: Warning: No PIN code in /var/tmp/portage/dev-python/python-gammu-2.5/temp/tmp40w59hdn/.gammurc file
Fri 2016/01/22 01:14:31 python-gammu[541]: Connected to Database sqlite3: smsd.db on localhost
Fri 2016/01/22 01:14:31 python-gammu[541]: Written message with ID 1
Fri 2016/01/22 01:14:31 python-gammu[541]: Written message with ID 2
Fri 2016/01/22 01:14:31 python-gammu[541]: Created POSIX RW shared memory at 0x7fcb84044000
Fri 2016/01/22 01:14:31 python-gammu[541]: Starting phone communication...
Fri 2016/01/22 01:14:31 python-gammu[541]: Inserting phone info
Fri 2016/01/22 01:14:32 python-gammu[541]: Read 2 messages
Fri 2016/01/22 01:15:02 python-gammu[541]: Terminating communication...
FAIL

======================================================================
FAIL: test_smsd (test.test_smsd.SMSDDummyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-gammu-2.5/work/python-gammu-2.5/test/test_smsd.py", line 118, in test_smsd
    status['Sent']
AssertionError: 0 != 2 : Messages were not sent as expected (0)!

----------------------------------------------------------------------
Ran 46 tests in 46.197s

FAILED (failures=1)
```

**Comment by sergiomb2** [comment]
Hello,
I can confirm that same error happens in Linux Fedora 22, 23 and Rawhide, I previous have 1 error , now I got 2 [1] 

I'd like also understand what means the other test error,as it is also about test_inject, I hope you don't mind : 

>test_inject (test.test_smsd.SMSDDummyTest) ... Log filename is "stderr"
>Wed 2016/01/20 02:49:05 python-gammu[30074]: Warning: No PIN code in /tmp/tmpvC4BMm/.gammurc file
>Wed 2016/01/20 02:49:05 python-gammu[30074]: DBI failed to initialize!
>ERROR
>test_smsd (test.test_smsd.SMSDDummyTest) ... Log filename is "stderr"
>Wed 2016/01/20 02:49:07 python-gammu[30074]: Warning: No PIN code in /tmp/tmpykcCJJ .gammurc file
>Wed 2016/01/20 02:49:07 python-gammu[30074]: DBI failed to initialize!
>ERROR

[1] 
https://kojipkgs.fedoraproject.org//packages/python-gammu/2.5/1.fc23/data/logs/x86_64/build.log

**Comment by nijel** [comment]
What Gammu version do you use for build?

**Comment by sergiomb2** [comment]
gammu-devel-1.36.8-1.fc23.x86_64

**Comment by awilfox** [comment]
Using 1.36.8 here as well, on a Gentoo system.

**Comment by nijel** [comment]
Can you please try building version from git? I've just added some logging to help analyze this issue.

**Comment by nijel** [comment]
Also did previous version build in same environment? It might just that you miss some of the dependencies for test (eg. sqlite3 dbi driver).

**Comment by sbraz** [comment]
@awilfox Is Python compiled with sqlite support? Tests pass for me with the same three Python version.

**Comment by sergiomb2** [comment]
Python is compiled with sqlite3 support. using commit f285defdcc34679f4cadac8313b0ba28c3b996be.patch
I got the same 2 errors:

    test_nothing (test.test_config.DebugTest) ... Gammu version (1, 36, 8), SMSD DB version 15
    Gammu version (1, 36, 8), SMSD DB version 15
    Gammu version (1, 36, 8), SMSD DB version 15
    python-gammu: WARNING: Adding USSD to queue, position 0
    ok
    ======================================================================
    ERROR: test_inject (test.test_smsd.SMSDDummyTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/python-gammu-2.5/test/test_smsd.py", line 84, in test_inject
        smsd.InjectSMS([MESSAGE_1])
    gammu.ERR_UNKNOWN: {'Code': 27, 'Where': 'SMSD_InjectSMS', 'Text': 'Unknown error.'}

    ======================================================================
    ERROR: test_smsd (test.test_smsd.SMSDDummyTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/builddir/build/BUILD/python-gammu-2.5/test/test_smsd.py", line 92, in test_smsd
        smsd.InjectSMS([MESSAGE_1])
    gammu.ERR_UNKNOWN: {'Code': 27, 'Where': 'SMSD_InjectSMS', 'Text': 'Unknown error.'}

    ----------------------------------------------------------------------
    Ran 46 tests in 17.769s

    FAILED (errors=2)

**Comment by nijel** [comment]
It doesn't matter if Python is compiled with sqlite3, it depends on Gammu being compiled with libdbi and it has installed dbi sqlite3 driver.

**Comment by sbraz** [comment]
@nijel Well the error is different but it's still required, right? https://github.com/gammu/python-gammu/blob/master/test/test_smsd.py#L29

**Comment by nijel** [comment]
Yes, it's required, but it would have failed already on importing the tests and not during run.

**Comment by nijel** [comment]
I've now added even more debugging, so it should bring more light...

**Comment by sergiomb2** [comment]
Hello , sorry after check again, I notice, I got other error , I can't connect to DBI and our reporter connects to DBI ! 

>  Connected to Database sqlite3: smsd.db on localhost

So I'm sorry , I have other issue , after digging a little I saw that also got test errors in gammu, I have to dig further ...

Best regards.

**Comment by nijel** [comment]
I've just released [Gammu 1.37.0](http://wammu.eu/download/gammu/1.37.0/) which does more verbose error reporting, so it would be more clear what went wrong...

**Comment by sergiomb2** [comment]
JFTR : I needed install package libdbi-dbd-sqlite, to pass these tests . 
My issue is solved with package gammu and package python-gammu.

Thanks and best regards

**Comment by iezed** [comment]
This line "from .test_dummy import DummyTes " from test_smsd it's correct ? Sorry for my english.

**Comment by nijel** [comment]
Yes the line is correct (assuming you are missing last t from the class name).

**Comment by awilfox** [comment]
It still does not work, however the log output is a lot more verbose.  As such I have put it [on a paste bin](https://code.foxkit.us/snippets/8) instead of pasting inline.

**Comment by nijel** [comment]
BTW: Does Gammu tests pass on the same system?

Maybe https://github.com/gammu/gammu/issues/177 is related as well...

**Comment by nijel** [comment]
I've fixed few corruption bugs which could cause this. Can you please retry that with today released gammu and python-gammu? See http://wammu.eu/

**Comment by nijel** [comment]
Assuming the issue is fixed.
